---
# Homepage configuration
# See https://fontawesome.com/search for icons options

title: "Pendrell Vale"
subtitle: "Welcome to"
logo: "assets/icons/tabernacle.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false

# Optional theme customization
theme: default

# Optional theme customization (color overrrides)
# overrrides can also be done using CSS vars
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

## Optional message
#message:
#  #url: https://b4bz.io
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  icon: "fa fa-grin"
#  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links: []
  # - name: "Contribute"
  #   icon: "fab fa-github"
  #   url: "https://github.com/bastienwirtz/homer"
  #   target: "_blank" # optional html a tag target attribute
  # - name: "Wiki"
  #   icon: "fas fa-book"
  #   url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Gallery"
    icon: "fas fa-fire"
    items:
      - name: "Jellyfin"
        icon: "fa-solid fa-film"
        url: "http://jellyfin.pendrellvale.home"
        target: "_blank"
      - name: "Immich"
        icon: "fa-solid fa-images"
        url: "http://immich.pendrellvale.home"
        target: "_blank"
      - name: "Navidrome"
        icon: "fa-solid fa-music"
        url: "http://navidrome.pendrellvale.home"
        target: "_blank"
      - name: "Minecraft"
        icon: "fa-solid fa-cube"
        url: "https://minecraft.mendess.xyz"
        target: "_blank"

  - name: "Tools"
    icon: "fas fa-wrench"
    items:
      - name: "Grafana"
        icon: "fa-solid fa-chart-line"
        url: "http://grafana.pendrellvale.home"
        target: "_blank"
      - name: "Planar Bridge"
        icon: "fa-solid fa-bullseye"
        url: "http://planar-bridge.mendess.xyz"
        target: "_blank"
      - name: "Mirrodin"
        icon: "fa-solid fa-robot"
        url: "http://mendess.xyz"
        target: "_blank"
      - name: "Nextcloud"
        icon: "fa-solid fa-cloud"
        url: "http://nextcloud.pendrellvale.home"
        target: "_blank"

  - name: "Alto Mar"
    icon: "fas fa-ship"
    items:
      - name: "Prowlarr"
        subtitle: "Pirate Captain"
        icon: "fa-solid fa-skull-crossbones"
        url: "http://prowlarr.pendrellvale.home"
        target: "_blank"
      - name: "Radarr"
        subtitle: "movies"
        icon: "fa-solid fa-film"
        url: "http://radarr.pendrellvale.home"
        target: "_blank"
      - name: "Sonarr"
        subtitle: "series"
        icon: "fa-solid fa-tv"
        url: "http://sonarr.pendrellvale.home"
        target: "_blank"
      - name: "Lidarr"
        subtitle: "music"
        icon: "fa-solid fa-music"
        url: "http://lidarr.pendrellvale.home"
        target: "_blank"
      - name: "Bazarr"
        subtitle: "subtitles"
        icon: "fa-solid fa-font"
        url: "http://bazarr.pendrellvale.home"
        target: "_blank"
      - name: "qBittorrent"
        icon: "fa-solid fa-download"
        url: "http://qbittorrent.pendrellvale.home"
        target: "_blank"
